export const ComonduTownshipTowns = [
  "Ciudad Constitución",
  "Puerto Adolfo López Mateos",
  "Agua Escondida",
  "El Aguajito Uno",
  "Álvarez Lote 5",
  "Andachires",
  "Puerto Magdalena",
  "Batequitos",
  "Benito Juárez",
  "Buenos Aires",
  "Cabo San Lázaro",
  "Cadejé",
  "La Calabaza",
  "Calejú",
  "Las Barrancas",
  "El Canelo",
  "El Cantil",
  "Carambuche",
  "Coahuila Lote 11",
  "La Escondida",
  "Jalisco Lote C6-K",
  "Francisco Villa",
  "La Frutilla Lote 2",
  "La Higuerita",
  "Ciudad Insurgentes",
  "Jesús María",
  "La Lomboyosa",
  "Magisterial Lote 611-2",
  "María Auxiliadora",
  "La Matancita",
  "El Ojo de Agua",
  "El Duguajal",
  "Palo Bola",
  "Los Paredones",
  "Paso Hondo",
  "Llano los Patitos Lote 3",
  "La Petaca",
  "Los Pilares",
  "El Porvenir",
  "La Poza Grande",
  "Puente de Madera",
  "Puerto Alcatraz",
  "Puerto Cortés",
  "La Purísima",
  "San Dionisio Quepo",
  "Rancho Nuevo",
  "Ramaditas",
  "San Agustín",
  "San Andrés",
  "San Antonio",
  "San Bartolo",
  "Puerto San Carlos",
  "San Eulogio",
  "San Isidro",
  "San José de Comondú",
  "San José de Guajademí",
  "San José de la Noria",
  "San Martín",
  "San Mateo Uno",
  "San Miguel de Comondú",
  "San Ramón",
  "Santa Rosa",
  "Santo Domingo",
  "Santo Tomás",
  "Siempre Viva",
  "Teotlán",
  "Las Tinajitas",
  "El Tulillo",
  "Villa Hidalgo",
  "Villa Morelos",
  "La Vinatería",
  "Villa Ignacio Zaragoza",
  "Ley Federal de Aguas Número Uno",
  "Ley Federal de Aguas Número Dos",
  "Ley Federal de Aguas Número Tres",
  "Ley Federal de Aguas Número Cuatro",
  "Ley Federal de Aguas Número Cinco",
  "Josefa Ortiz de Domínguez",
  "Tepentú",
  "Los Achemes",
  "El Aguajito",
  "La Pila",
  "El Batequi",
  "Las Bebelamas",
  "Boca de San Carlos",
  "Calagua",
  "Puerto Cancún",
  "La Casita",
  "Los Cerritos",
  "El Chamizal Lote 14",
  "El Chicural",
  "El Chipí",
  "El Codey",
  "El Conejo",
  "El Corralito",
  "El Coyote",
  "El Crucerito",
  "La Cruz",
  "Cuedas",
  "La Cueva",
  "El Frijol",
  "El Rincón de las Garzas",
  "El Gramal",
  "El Higuajil",
  "La Huerta",
  "Las Jarillas",
  "Laredo",
  "Los Mezquitones",
  "Las Norias",
  "San Juan de la Cruz",
  "El Pabellón",
  "Los Pájaros",
  "Palo Fierro",
  "Los Palos Verdes",
  "El Pato",
  "La Picota",
  "Las Pimientillas",
  "La Pocita",
  "El Portezuelo",
  "La Poza del Bule",
  "La Poza del Gato",
  "La Poza del León",
  "La Poza Larga",
  "La Poza Muerta",
  "La Ramadita",
  "El Ranchito",
  "El Refugio",
  "El Saltito",
  "San Bernardo",
  "San Buto [Campo Pesquero]",
  "San Cipriano",
  "San Ignacio",
  "San José del Parral",
  "San Juan",
  "San Luisito",
  "San Miguel de Velázquez",
  "San Venancio",
  "Santa Adelaida",
  "Santa Isabel",
  "Santa Teresa",
  "El Saucito",
  "El Sauzal",
  "El Sauzalito",
  "La Selva",
  "El Tajo",
  "El Tequesquite",
  "La Tórtola",
  "El Veladero",
  "La Vinata",
  "San Luis Gonzaga",
  "San Vicente",
  "El Aviadero",
  "Las Higueritas",
  "Valenzuela",
  "El Molino",
  "El Agua Libre",
  "Fernando de la Toba (Los Algarrobos)",
  "El Carricito",
  "Rancho Covarrubias",
  "El 49",
  "Los Cuatro Corrales",
  "El Junco",
  "Kilómetro 228",
  "Álvarez Lote 8",
  "Los Médanos",
  "Las Delicias Lote 33",
  "El Mezquitito",
  "San Isidro Labrador",
  "El Pedregal",
  "Álvarez Lote 25",
  "El Potrero",
  "San Antonio de la Montaña",
  "Nueva California Lote 29",
  "San Gregorio",
  "San Pedrito",
  "Emiliano Zapata Lote 6",
  "Nueva California Lote 33",
  "Los Torunos",
  "El Triunfo",
  "Yerbabuena",
  "Fernando de la Toba Lote 39",
  "El Aguajito de Tepentú",
  "El Agua Grande",
  "El Agua Puerca",
  "Los Algodones",
  "Fernando de la Toba Lote 131",
  "Fernando de la Toba Lote 85",
  "Buenos Aires Lote 5",
  "Los Arquitos",
  "Fernando de la Toba Lote 142",
  "El Atorón",
  "La Bandera",
  "La Boca del Viejo",
  "La Bocana de San Gregorio",
  "Los Burros",
  "La Calera",
  "La Cerquita",
  "El Chicural de la Relumbrosa",
  "Los Chorros",
  "Agua Clarita",
  "Álvarez Lote 17",
  "Jalisco (El Coto)",
  "Las Cruces",
  "El Dulce",
  "La Mesa del Carro Quemado",
  "La Esperanza",
  "Rancho Estrada",
  "Álvarez Lote 31",
  "Fernando de la Toba Lote 144",
  "Las Gaviotas",
  "Ejido Santo Domingo Grupo 2",
  "Ejido Santo Domingo Grupo 9",
  "Ejido Santo Domingo Grupo 8",
  "Ejido Santo Domingo Grupo 25",
  "La Herradura",
  "El Imposible",
  "Jalisco Lote C3-Y",
  "El Infiernito",
  "El Jarillal",
  "Las Joyitas",
  "El Juncalito",
  "Tinaja de la Laguna",
  "La Laguna de Afuera",
  "Álvarez Lote 19",
  "El Liberato",
  "El Llano Blanco",
  "Loma Alta",
  "El Malvar",
  "María Auxiliadora Lote 4",
  "La Mascota",
  "Matancitas",
  "Médano Amarillo",
  "El Medio Corral",
  "La Mochilla",
  "Los Naranjos",
  "San Nicolás",
  "Emiliano Zapata Lote 24",
  "Buenos Aires Lote 40",
  "El Pailabote",
  "Jalisco Lote C6-P (Las Palmas)",
  "La Palmita",
  "El Palo Verde",
  "Jalisco Lote C6-D (Palos Verdes)",
  "Los Panales",
  "Parácuaro",
  "Jalisco Lote C3-X",
  "El Paraíso",
  "Fernando de la Toba Lote 143",
  "Piedras Paradas",
  "Las Pilas",
  "Los Tepetates",
  "La Poza del Ciruelo",
  "Poza Honda",
  "Poza Honda Dos",
  "Poza Sola Dos",
  "Jalisco (El Pozo Peña)",
  "Las Puntas",
  "Purísima Vieja",
  "El Quemadito",
  "Jalisco Lote 5-0",
  "Galeana Lote 15-A",
  "El Salvador",
  "San Cristóbal",
  "San Francisco de Tepentú",
  "San Jacinto",
  "San José",
  "San José del Romerillal",
  "San Julián",
  "San Carlos Lote 511-4",
  "San Miguel de Quepo",
  "San Pedro",
  "San Rafael Uno",
  "Fernando de la Toba Lote 140",
  "Santa María",
  "Acatic Lote 403",
  "Santo Niño de Atocha (Romerillal)",
  "El Sauce",
  "El Seguro",
  "Rincón Grande",
  "La Tinaja del Burro",
  "El Tiradero",
  "Los Pinos",
  "La Trinidad",
  "Buenos Aires Lote 46",
  "Fernando de la Toba Lote 138",
  "Buenos Aires Lote 28",
  "La Vinatería Dos",
  "Capí",
  "El Juncal",
  "Punta Arenas",
  "La Bartolina",
  "San Juan de Matancitas Lote 1",
  "San Juan de Matancitas Lote 4",
  "San Fidencio",
  "El Rosario",
  "Los Álvarez",
  "El Cincuentaidós",
  "La Manglosa",
  "La Purísima (Los Pinos)",
  "La Purísima Lote C2",
  "La Purísima Lote 3",
  "Jalisco Lote C2-0",
  "Jalisco Lote C3-P",
  "Jalisco Lote C3-W",
  "Jalisco Lote C3",
  "Jalisco Lote C-251",
  "Jalisco (Rancho González)",
  "María Auxiliadora Lote 7-A",
  "María Auxiliadora Lote 10",
  "María Auxiliadora (El Mompala)",
  "Jalisco Lote C3-B",
  "Jalisco Lote NC5",
  "Jalisco Lote C5-R",
  "Álvarez Lote 9",
  "Álvarez Lote 15",
  "Álvarez Lote 13",
  "Álvarez Lote 14",
  "Galeana Lote sin Número",
  "Galeana Lote 7",
  "Galeana Lote 15",
  "Galeana Lote 10",
  "Galeana Lote 13",
  "Álvarez Lote 34",
  "Galeana Lote 20",
  "Palos Altos Lote 5",
  "Galeana Lote 16",
  "Palos Altos Lote 3",
  "Palos Altos Lote 2",
  "Fierro Encinas Dos Lote 16",
  "Galeana Lote 11",
  "Galeana Lote 22",
  "Galeana Lote 40",
  "Galeana Lote 37",
  "Galeana Lote 23",
  "Palos Altos Lote 8",
  "Palos Altos Lote 1",
  "Galeana Lote 35",
  "Galeana Lote 34",
  "Galeana Lote 28",
  "Fierro Encinas Dos Lote 21",
  "Fierro Encinas Dos Lote 49",
  "Buenos Aires Lote 43",
  "Fierro Encinas Dos Lote 23",
  "Fierro Encinas Dos Lote 13",
  "La Mascota Lote 6",
  "La Mascota Lote 7",
  "Buenos Aires Lote 36",
  "Buenos Aires Lote 54",
  "Buenos Aires Lote 35",
  "Buenos Aires Lote 20",
  "Buenos Aires Lote 11",
  "Buenos Aires Lote 8",
  "Buenos Aires Lote 9",
  "Buenos Aires Lote 10",
  "Fernando de la Toba Lote 81",
  "Fierro Encinas Uno Lote 2",
  "Fernando de la Toba Lote 132",
  "Buenos Aires Lote 45",
  "Buenos Aires Lote 41",
  "Fernando de la Toba Lote 66",
  "Fernando de la Toba Lote 48",
  "Fernando de la Toba Lote 49",
  "Fernando de la Toba Lote 41",
  "Fernando de la Toba Lote 51",
  "Fernando de la Toba Lote 60",
  "Fernando de la Toba Lote 61",
  "Santa Fe Uno Lote F",
  "Buenos Aires Lote 32",
  "Buenos Aires Lote 22",
  "Buenos Aires Lote 23",
  "Buenos Aires Lote 24",
  "Buenos Aires Lote 18",
  "Fernando de la Toba Lote 73",
  "Fernando de la Toba Lote 44",
  "Fernando de la Toba Lote 54",
  "Fernando de la Toba Lote 55",
  "Fernando de la Toba Lote 63",
  "Fernando de la Toba Lote 88",
  "Fernando de la Toba Lote 139",
  "Chihuahua Lote 4-A",
  "Navojoa Uno Lote 6",
  "La Laguna Lote 55",
  "Navojoa Uno Lote 7",
  "Fernando de la Toba Lote 145",
  "La Laguna Lotes 36 y 37",
  "La Laguna Lote 38",
  "La Laguna Lotes 46 y 47",
  "La Laguna Lotes 16 y 17",
  "La Laguna Lote 54",
  "La Laguna Lote 52",
  "Nayarit Lote 6",
  "Río Mayo Lote 15",
  "Río Mayo Lote 7",
  "Nayarit Lote 4",
  "Nayarit Lote 3",
  "Dieciocho de Marzo Lote 4",
  "Villa Hidalgo Lote 29",
  "Río Mayo Lote 8",
  "Río Mayo Lote 12",
  "Fernando de la Toba Lote 89",
  "Nuevo Jiménez Lote 24",
  "Nueva Jiménez Lote 3",
  "Fernando de la Toba Lote 47",
  "Fernando de la Toba Lote 28",
  "Fernando de la Toba Lote 17",
  "Fernando de la Toba Lote 26",
  "Nuevo Jiménez Lote 38",
  "Nuevo Jiménez Lote 29",
  "Nueva Jiménez Lote 31",
  "Nuevo Jiménez Lote 36",
  "Nuevo Jiménez Lote 14",
  "La Pitahaya",
  "Mexicali Lote 23",
  "Campo Plascencia",
  "Mexicali Lote 10",
  "Fernando de la Toba Lote 5",
  "Fernando de la Toba Lote 7",
  "Agustín Olachea Lotes 4 5 12 y 11",
  "Agustín Olachea Lotes 6 7 13 y 14",
  "Fernando de la Toba Lote 8",
  "Sinaloa Lote 15",
  "Sinaloa Lote 17",
  "Sinaloa Lote 18",
  "Sinaloa Lote 28-A",
  "Sinaloa Lote 20",
  "Nueva California Lote 75",
  "Nueva California Lote 78",
  "Nueva California Lote 88",
  "Nueva California Lote 96",
  "Fernando de la Toba Lote 20",
  "Fernando de la Toba Lote 29",
  "México Lote 1",
  "Fernando de la Toba Lote 10",
  "Fernando de la Toba Lote 22",
  "Fernando de la Toba Lote 33",
  "Fernando de la Toba Lote 25",
  "Fernando de la Toba Lote 34",
  "Nuevo Jiménez Lote 6",
  "Nueva Jiménez Lote 1",
  "Nuevo Jiménez Lote 8",
  "Nuevo Jiménez Lote 11",
  "Nuevo Jiménez Lote 15",
  "Nuevo Jiménez Lote 16",
  "Nuevo Jiménez Lote 30",
  "Cuauhtémoc",
  "Norte Lote 1",
  "Mexicali Lote 2",
  "Mexicali Lote 4",
  "Campo Peña (Romerillal)",
  "El Romerillal",
  "Mexicali Lote 18-A",
  "Nueva California Lote 83",
  "Nueva California Lote 72",
  "Fernando de la Toba Lote 3",
  "México Lotes 4 y 5",
  "Río Mayo Lote 14",
  "México Lote 6",
  "Fernando de la Toba Lote 76",
  "Fernando de la Toba Lote 87",
  "Nuevo Jiménez Lote 4",
  "Nuevo Jiménez Lote 9",
  "Nuevo Jiménez Lote 10",
  "Nuevo Jiménez Lote 27",
  "Mexicali Lote 6",
  "Mexicali Lote 11",
  "Mexicali Lote 1",
  "Cuauhtémoc Lote 2",
  "Cuauhtémoc Lote 1",
  "Nueva California Lote 101",
  "Nueva California Lote 90",
  "La Presa del Higuajil",
  "Progreso Lote 18",
  "Progreso Lote 19",
  "Progreso Lote 14",
  "San Francisco Javier",
  "Nueva California Lote 15",
  "Nueva California Lote 12",
  "Nueva California Lote 8",
  "Ejido Matancitas Grupo 9",
  "Nueva California Lote 42",
  "Nueva California Lote 45",
  "Nueva California Lote 44",
  "Nueva California Lote 58",
  "Nueva California Lote 57-A",
  "Nueva California Lote 60",
  "Gallo Loco Lote 4",
  "Gallo Loco Lote 3",
  "Cuitláhuac Lote 18",
  "Cuitláhuac Lote 24",
  "Cuitláhuac Lote 31",
  "Cuitláhuac Lote 37",
  "Cuitláhuac Lote 30",
  "Cuitláhuac Lote 23",
  "Gallo Loco Lote 1",
  "Nueva California Lote 32",
  "Nueva California Lote 16",
  "Nueva California Lote 17",
  "Nueva California Lote 23",
  "Nueva California Lote 21",
  "Nueva California Lote 59",
  "Sinaloa Lote 7",
  "Sinaloa Lote 3",
  "Agustín Olachea Lote 39",
  "Norte Lote 5",
  "Norte Lote 6",
  "Nueva California Lote 3",
  "Los Tulares Lote 2-B",
  "Nueva California Lote 66",
  "Nueva California Lote 67",
  "Nueva California Lote 61",
  "Nueva California Lote 49",
  "Nueva California Lote 62",
  "Nueva California Lote 48",
  "Nueva California Lote 35",
  "Nueva California Lote 38",
  "Nueva California Lote 55",
  "Salvatierra Lote 8",
  "Salvatierra Lote 4",
  "Cuitláhuac Lote 3",
  "Cuitláhuac Lote 6",
  "Salvatierra Lote 5",
  "Cuitláhuac Lote 51",
  "Cuitláhuac Lote 44",
  "Cuitláhuac Lote 45",
  "Cuitláhuac Lote 52",
  "Cuitláhuac Lote 46",
  "Cuitláhuac Lote 32",
  "Cuitláhuac Lote 47",
  "Salvatierra Lote 25",
  "Las Olas Altas",
  "El Camarillo",
  "El Vallecito",
  "El Sacramento",
  "Revolución Mexicana Lote 93",
  "Revolución Mexicana Lote 94",
  "El Vivero",
  "Ninguno [Campamento SCT]",
  "Emiliano Zapata Lote 2-B",
  "La Pila [Club Campestre]",
  "Don Pelayo",
  "Misión Lote 20",
  "Guadalajara Lote 9",
  "Guadalajara Lote 13",
  "Guadalajara Lote 7",
  "Emiliano Zapata Lote 23",
  "Cuitláhuac Lote 34",
  "Ninguno [Procesadora Agropecuaria]",
  "Salvatierra Lote 23",
  "Vargas Lote 1",
  "El Venadito",
  "Revolución Mexicana Lote 90",
  "Los Ocampo",
  "El Buterfiel",
  "Colonia Agrícola Revolución Mexicana",
  "Revolución Mexicana Lote 91",
  "Guanajuato Lote 8",
  "Emiliano Zapata Lote 7",
  "Emiliano Zapata Lote 8",
  "Emiliano Zapata Lote 11",
  "Guanajuato Lote 13",
  "Llano Verde Lote 4",
  "Llano Verde Lote 1",
  "Emiliano Zapata Lote 21",
  "Cuitláhuac Lote 49",
  "Cuitláhuac Lote 42",
  "Cuitláhuac Lote 43",
  "Cuitláhuac Lote 50",
  "Colonia Agrícola Salvatierra",
  "Salvatierra Lote 27",
  "San Felipe",
  "Los Camachos",
  "Revolución Mexicana Lote 50",
  "Revolución Mexicana Lotes 87 y 88",
  "Revolución Mexicana Lotes 63 y 64",
  "Guanajuato Lote 4",
  "Guanajuato Lote 5",
  "Rancho Dos Hermanos",
  "Emiliano Zapata Lote 3",
  "Emiliano Zapata Lote 5",
  "Guanajuato Lote 6",
  "Misión Lote 3",
  "Misión Lote 12",
  "Llano los Patitos Lote 5",
  "Guanajuato Lote 23",
  "Misión Lote 11",
  "Yaquis Lote 18",
  "Yaquis Lote 26",
  "Yaquis Lote 13",
  "Yaquis Lote 14",
  "Yaquis Lote 21",
  "El Vergel Lote 28",
  "El Vergel Lote 25",
  "El Vergel Lote 24",
  "San Carlos Lote 507-1",
  "San Carlos Lote 605-3",
  "San Carlos Lote 507-4",
  "Yaquis Lote 1",
  "Yaquis Lote 8",
  "Yaquis Lote 9",
  "Yaquis Lote 16",
  "Yaquis Lote 22",
  "Las Delicias Lote 47",
  "El Vergel Lote 29",
  "El Vergel Lote 1",
  "Las Delicias Lote 42",
  "Las Delicias Lote 34",
  "Las Delicias Lote 35",
  "San Carlos Lote 511-1",
  "Navojoa Dos Lote 3",
  "Misión Lote 13",
  "Misión Lote 8",
  "Misión Lote 21",
  "Las Delicias Lote 7",
  "Agustín Olachea Lote 3",
  "Barranca de Otates Lote 14",
  "Barranca de Otates Lote 13",
  "El Capricho",
  "Nuevo Linares",
  "Poza Sola 3",
  "San Juan de las Lagunetas",
  "El Canutillo (Los Cacumes)",
  "El Mezquital Seco",
  "Ejido Santo Domingo Grupo 11",
  "Ejido Santo Domingo Grupo 12",
  "El Puga",
  "Casas Viejas",
  "El Zapote",
  "El Salto",
  "Los Dormideros",
  "Llano Catarina",
  "El Abanico",
  "La Zavalsa",
  "Palo Verde",
  "San Juanico",
  "La Yaqui",
  "La Venada",
  "La Ballena",
  "El Mezquite",
  "El Agua Zarca",
  "El Cardón",
  "El Chencho",
  "El Cantiloso",
  "Mesa la Ceribosa",
  "El Llano",
  "La Piedra",
  "La Becerrita",
  "El Rincón de la Perra",
  "Los Tres Reyes",
  "La Poza",
  "El Tanque del Mezquite",
  "La Pedregosa",
  "El Datilón",
  "Dieciocho de Marzo Lote 11",
  "Sinaloa Lote 22",
  "Buenos Aires Lote 39",
  "Buenos Aires Lote 38",
  "La Ventana",
  "El Agua Honda",
  "El Secreto",
  "Fierro Encinas Dos Lote 11",
  "Buenos Aires Lote 6",
  "Buenos Aires Lotes 1 y 1B",
  "Álvarez Lote 2",
  "Salvatierra Lote 1",
  "Sinaloa Lote 6",
  "Fernando de la Toba Lote 62",
  "Jalisco Lote C1-O",
  "Jalisco Lote C2-K",
  "Jalisco (Palos Verdes C6-B)",
  "Jalisco (Palos Verdes C6-C)",
  "Galeana Lote 8",
  "Galeana Lote 27",
  "San Juan Bosco Lote 6",
  "Fierro Encinas Lote 15",
  "San Rafael",
  "Los Perdidos",
  "Buenos Aires Lote 44",
  "Ninguno [CBTA 27]",
  "Fernando de la Toba Lote 83",
  "Fernando de la Toba Lote 68",
  "Las Avispas",
  "Fernando de la Toba Lote 50",
  "Fernando de la Toba Lote 56",
  "Río Mayo Lote 10",
  "Río Mayo Lote 5",
  "Río Mayo Lote 3",
  "Nueva California Lote 82",
  "Nueva California Lote 99",
  "Guadalajara Lote 2-A",
  "Guadalajara Lote 1",
  "Guanajuato Lote 19",
  "La Laguneta",
  "San Lorenzo",
  "Guadalupe de la Picota",
  "El Paisano",
  "El Chamizal Lote 5",
  "El Chamizal Lote 10",
  "San Silvestre",
  "El Cielo",
  "Sinaloa Lote 12",
  "Sinaloa Lote 21",
  "Los Cajoncitos",
  "El Ojito de Agua",
  "El Cajón",
  "Ejido Santo Domingo Grupo 31",
  "Ejido Santo Domingo Grupo 23",
  "El Chamizal Lote 1-8",
  "Ejido Santo Domingo Grupo 4",
  "Ejido Santo Domingo Grupo 5",
  "La Purísima Lote C3-F",
  "La Purísima Lote C3-G",
  "Jalisco Lote C3-MVW",
  "Fierro Encinas Dos Lote 1",
  "Fierro Encinas Dos Lote 5",
  "Fierro Encinas Dos (Rancho Celis)",
  "Santa Fe Dos Lote 71",
  "Santa Fe Dos Lote 71-A",
  "Ley Federal de Aguas Número Uno Lote 3",
  "Ley Federal de Aguas Número Uno Lote 8",
  "La Laguna Lotes 26 y 27",
  "Río Mayo Lote 2",
  "Villa Hidalgo Lote 28",
  "Mexicali Lote 12",
  "Sinaloa (Frutales del Valle)",
  "Salvatierra (Las Bramonas)",
  "Ejido la Granada Lote 23",
  "Las Delicias Lote 9",
  "El Pozo Número Uno",
  "El Toro",
  "Las Compostelas (El Sacrificio)",
  "Las Compostelas (Las Isabeles)",
  "Flores Rodríguez Lote 2",
  "Cerro Gordo",
  "La Barrita",
  "El Agua Escondida",
  "El Agua Relumbrosa",
  "Calderón",
  "El Cardal",
  "El Cardón Escrito",
  "Familia Carrillo",
  "El Chicharrón",
  "La Chuparrosa",
  "Fernando de la Toba Lote 130",
  "Fernando de la Toba (Ferinsa)",
  "Fernando de la Toba Lote 38",
  "Jalisco Lote 5 C3MZM",
  "La Purísima Lote MZ1",
  "Las Delicias (Rancho Guzmán)",
  "Nueva California Lote 57-B",
  "Revolución Mexicana Lote 77",
  "Sinaloa Lote 8",
  "La Cuestecita",
  "El Desengaño",
  "Las Estiladeras",
  "Grupo Solidario Hermanos Ocampo",
  "La Jícama",
  "El Mauto",
  "Mesa de las Mulas",
  "El Mezquital",
  "La Muñeca",
  "La Pimientilla",
  "Los Prados",
  "Rancho Calderón",
  "La Laguna del Mezquital",
  "San Lucas",
  "El Nayo",
  "Llano de la Perra",
  "Las Tinajas",
  "Escorpión Beach",
  "La Travesía",
  "Fernando de la Toba Lote 126",
  "El Aparejo",
  "San Miguel",
  "Kilómetro 54",
  "Ejido Matancitas Grupo 10 F-13",
  "Las Lomas",
  "Palo Alto",
  "El Tezo",
  "Emiliano Zapata (La Granja)",
  "Fierro Encinas Lote 18",
  "Guadalajara Lote 24-A",
  "Jalisco Lote C3-T",
  "Santa Fe Lote G",
  "Ley Federal de Aguas Número Cinco Pozo 22",
  "Las Garzas",
  "Rancho el Abrevadero",
  "El Nuevo Capricho",
  "Los Varelas",
  "Magisterial (Rancho Ocampo)",
  "El Abrevadero del Tres",
  "El Remendado",
  "Agustín Olachea Lote 4",
  "Rancho Espinoza",
  "Ley Federal de Aguas Número Cinco Pozo 3 Yaki",
  "San Judas Tadeo",
  "El Pozo Número Dos",
  "Las Delicias Lote 27",
  "Los Tules",
  "La Paila",
  "Ninguno",
  "El Cuatro",
  "El Carrizalito",
  "La Curva",
  "El Temblor",
  "Los Cantiles",
  "Loma Linda",
  "Los Girasoles",
  "El Esterón",
  "El Choyal",
  "La Sábila",
  "La China",
  "San Antonio de Batequitos",
  "Las Veredas",
  "La Torre",
  "Bebelamas",
  "El Caimán",
  "Los Tres Potrillos",
  "El Milagro",
  "El Molino de Batequitos",
  "La Curvita [Restaurante]",
  "El Bule",
  "El Pedregal de San Luis",
  "El Potrillo",
  "Las Palmas de San Luis",
  "El Malverde",
  "Rancho Valverde",
  "San Jorge",
  "Fernando de la Toba Lote 79",
  "Cuitláhuac Lote 28",
  "El Batequito",
  "Boca del Arroyo",
  "El Lloradero",
  "El Divino Niño Jesús",
  "Bateque Lino",
  "El Alto",
  "El Dátil",
  "El Limón",
  "El Relevo",
  "Juan Diego",
  "La Carrera",
  "La Carrerita",
  "La Tunita",
  "Las Jaras",
  "Los Metatitos",
  "Santa Fe del Río",
  "Ojo de Agua",
  "Paso Colorado",
  "Rancho Escondido",
  "San Judas de Batequitos",
  "Buenos Aires Lote 48",
  "El Aeropuerto",
  "La Pitaya",
  "Las Elenas",
  "Los Gallos",
  "La Trituradora del Kilómetro Tres",
  "Piedra Sola",
  "Las Palmas",
  "El Eucalipto",
  "El Indomable",
  "La Joya",
  "Las Tres Palmas",
  "Paso de Romo",
  "San José de Batequitos",
  "San Juan de Matancitas",
  "Campo 95",
  "Las Lágrimas",
  "El Palo Fierro",
  "La Laguna",
  "La Loma",
  "El Imperio Verde",
  "Salvatierra Lote 68",
  "San Francisco",
  "Agroproductos las Cumbres",
  "La Virgencita II",
  "La Virgencita",
  "San Ignacio Uno",
  "Camino Real",
  "La Poza de Silverio",
  "La Colorada",
  "Las Flores",
  "Rancho San Juan",
  "Rancho Rastrillo",
  "El Renegado",
  "Camino del Medio",
  "La Majada",
  "Nueva Vida",
  "El Quemado",
  "Las Hermanas",
  "Cuitlahuac Lote 36",
  "Los Cascabeles",
  "El Colorín",
  "Los Crestones",
  "El Abanico Dos",
  "La Subida Alta",
  "Paso Blanco",
  "El Sacrificio",
  "La Mesita Alta",
  "Corral Falso",
  "Piedra Pesada",
  "El Llano Redondo",
  "San Juan de Dios"
]