export const LaPazTownshipTowns = [
  "La Paz",
  "Todos Santos",
  "Agua Amarga",
  "Agua Blanca",
  "Agua de Enmedio",
  "El Agua Ademada",
  "El Aguajón",
  "El Agüita",
  "La Aguja",
  "Los Algodones Uno",
  "Las Ánimas",
  "La Ardilla",
  "La Banderita",
  "Las Bebelamas 2",
  "Las Bebelamas",
  "Boca del Sauzoso",
  "El Cayuco",
  "Las Breyitas",
  "Buenaventura",
  "Buenavista",
  "Los Burritos",
  "El Cajoncito",
  "Las Calabazas",
  "La Campana",
  "El Centenario",
  "El Conejo",
  "Chametla",
  "El Chivato",
  "El Dátil",
  "El Datilito",
  "San Rafael de los Encinitos",
  "Ensenada de Cortés",
  "El Estero",
  "La Fortuna",
  "Guadalupe",
  "La Huerta",
  "Huertas Viejas",
  "San Rafael de los Inocentes",
  "El Calí",
  "La Matancita",
  "Matancitas",
  "La Matanza",
  "El Médano",
  "Nopoló",
  "Santa Clara",
  "La Palmilla",
  "El Palo Verde",
  "Las Paredes",
  "Pénjamo [Restaurante]",
  "El Pilar",
  "El Porvenir",
  "Las Pocitas",
  "El Pozo de Rodríguez",
  "La Primer Agua",
  "Puerto Chale",
  "La Purificación",
  "El Quelele",
  "Los Robles",
  "El Rosario Uno",
  "San Andrés",
  "El Cebú",
  "San Fermín",
  "San Francisquito",
  "San Jerónimo",
  "San Hilario",
  "San Pedro",
  "San Martín",
  "San Miguel",
  "San Patricio",
  "San Ramón",
  "Santa Cruz",
  "Tepeyac Santa Fe",
  "Santa Rita",
  "Santa Rita del Coyote",
  "El Saucito",
  "La Soledad",
  "Los Tamales",
  "Los Tejones",
  "El Tepetate",
  "La Trinidad",
  "La Victoria",
  "El Ocotillo",
  "Agua Caliente",
  "El Agua de Enmedio",
  "Agua de la Costa",
  "El Agua de León",
  "El Agua de López",
  "El Aguaje",
  "El Álamo",
  "Los Aguajitos",
  "Los Algodones",
  "Álvaro Obregón",
  "Bajada de la Mesa",
  "La Bajada del Molino",
  "Los Barriles",
  "El Bateque",
  "Boca del Álamo",
  "Boca del Saucito",
  "Buenos Aires",
  "Ángel de la Guarda",
  "Los Caballeros",
  "La Calerita",
  "Cananea",
  "El Carrizal",
  "Casa Blanca",
  "Las Casas Viejas",
  "Casas Viejas",
  "El Cerro Blanco",
  "La Cieneguita",
  "Ejido Plutarco Elías Calles",
  "La Concepción",
  "El Coro",
  "El Corral Falso",
  "Corral Falso",
  "Los Correderos",
  "Covarrubias",
  "Oasis San Jorge",
  "Cuernavaca",
  "San Fermín (La Cuesta)",
  "El Datilar",
  "Las Delicias",
  "El Desecho",
  "Los Divisaderos",
  "El Encinito",
  "Los Encinos",
  "Ensenada de Muertos",
  "La Esperanza",
  "San Jorge de la Mezcalera",
  "El Guayabito",
  "El Iguajil",
  "El Huatamote",
  "San José de la Palmilla",
  "La Línea",
  "Los Llanitos",
  "Los Llanos de Kakiwi",
  "El Mezquite",
  "El Mezquitillo",
  "La Muela",
  "Las Palmas",
  "La Palma Uno",
  "El Palmar de Abajo",
  "El Palmar de Enmedio",
  "El Palmarito",
  "La Palmillita",
  "El Palo de Arco",
  "Palo Escopeta",
  "Los Palos Verdes",
  "Palo Verde",
  "Los Paderones",
  "El Parralito",
  "El Pescadero",
  "Las Piedras Coloradas",
  "San Pedro de la Presa",
  "Las Piedritas",
  "El Pintado",
  "San Juan de los Planes",
  "Las Playitas",
  "El Potrerito",
  "El Potrero",
  "El Pozo",
  "El Refugio",
  "El Rosario 2",
  "El Rosarito",
  "El Saltito de los García",
  "San Antonio",
  "San Bartolo",
  "San Dionisio",
  "San Evaristo",
  "San Gabriel",
  "San Ignacio",
  "San Isidro",
  "San Jacinto",
  "San Joaquín",
  "San José del Rancho",
  "San Juan",
  "San Juan de Dios",
  "San Lorenzo",
  "San Luis",
  "San Marcos",
  "San Simón",
  "Santa Ana",
  "Santa Inés",
  "Santa Lucía",
  "Santa María",
  "Santa Rosa",
  "Santa Teresa",
  "Santo Domingo de la Sierra",
  "Santo Domingo",
  "San Venancio",
  "San Vicente",
  "San Vicente de la Sierra",
  "Los Taraices",
  "Las Termópilas",
  "Texcalama",
  "Las Tijeras",
  "Las Tinas",
  "Las Tres Pachitas",
  "El Triunfo",
  "Los Troncones",
  "El Tunal",
  "El Valle Perdido",
  "La Ventana",
  "La Veta",
  "La Vinatería",
  "La Vinorama",
  "Las Vinoramas",
  "Melitón Albáñez Domínguez",
  "Alfredo V. Bonfil",
  "Agua del Barro",
  "El Primer Bosque",
  "La Fortuna del Bajío",
  "Kilómetro 128",
  "El Saladito",
  "La Piedra Pintada",
  "San Juan de la Costa",
  "La Poza de Venancio",
  "Guadalupe de la Herradura Número Uno",
  "Los Tres Hermanos",
  "NCPE Conquista Agraria",
  "Chapingo",
  "El Copalito",
  "San Luciano",
  "La Estela",
  "Las Cruces",
  "Puerto Mejía",
  "El Cardón",
  "San Primitivo",
  "General Juan Domínguez Cota",
  "Los Ángeles",
  "Los Laureles",
  "El Pitahayal",
  "Santo Tomás",
  "El Ciruelito",
  "Las Carpas",
  "San Ángel",
  "San Fernando",
  "El Ancón",
  "Santa Isabel",
  "El Ciruelón",
  "Rancho Jazmin (Santa Teresita)",
  "El Cardonoso",
  "El Salto",
  "El Crucero",
  "El Veladero",
  "El Tezal",
  "La Última Agua",
  "La Reforma",
  "El Inquieto",
  "Punta Lobos",
  "Los Crestones",
  "Las Lagunillas",
  "Los Cuatro Vientos",
  "La Cuesta",
  "El Remudadero",
  "El Palmar del Balvino",
  "Casas de Abajo",
  "La Casita Vieja",
  "San Pedro México",
  "El Garbancillo",
  "Las Lisas",
  "El Ciruelar",
  "La Parra",
  "La Trinchera",
  "El Agua de los Coyotes",
  "El Aguajito",
  "Santa María del Oro",
  "El Anzarito",
  "Los Arenales",
  "La Arenosa",
  "El Bainoro",
  "El Bajío",
  "La Bolsa",
  "Dos de Abril (Buenavista)",
  "Los Bules",
  "Las Cabrillas",
  "San Blas del Cajoncito",
  "El Candelillal",
  "La Canelita",
  "El Cantilito",
  "El Cantil",
  "La Casa Blanca",
  "El Cocuyo",
  "El Confeti",
  "La Escondida",
  "La Estrella del Norte",
  "Las Flores",
  "La Garita",
  "Los Gavilanes",
  "Campo Agrícola HH",
  "El Guamúchil",
  "Las Higuerillas",
  "Kilómetro Ciento Diecisiete",
  "La Mariguana",
  "Don Mariano",
  "Dos de Abril (El Mezquite)",
  "El Motor",
  "La Joya",
  "Las Parras",
  "Los Pavoreales",
  "El Pirul",
  "Los Pocitos",
  "La Posta",
  "El Pozo Hondo",
  "Las Praderas",
  "Dos de Abril (La Providencia)",
  "El Rancho",
  "El Rebalse",
  "El Retiro",
  "La Reyna",
  "Rincón del León",
  "San Miguel del Salto",
  "Dos de Abril (San Antonio)",
  "San Bernardo",
  "San Carlos",
  "San Clemente",
  "Dos de Abril (San Francisco Lanzer)",
  "San Francisco de las Huertitas",
  "Dos de Abril (San Isidro)",
  "Dos de Abril San José",
  "San Pablo",
  "Dos de Abril (San Pedro)",
  "Santa Cecilia",
  "Santa Susana",
  "Dos de Abril (Santa Victoria)",
  "La Semilla",
  "El Sifón",
  "Los Tepetates",
  "El Trampuchete",
  "Aguajito de Castro",
  "El Aguajito de Moreno",
  "Mi Ranchito",
  "Las Arenas",
  "El Arroyo Seco",
  "Los Azabaches",
  "Bellavista",
  "El Bledito",
  "Bola de Fuego",
  "Los Brasileros",
  "La Buena Mujer",
  "La Cacachila",
  "El Camarón",
  "Ninguno [Campamento Forestal]",
  "La Canoa",
  "El Cardonal",
  "Agroexportadora del Noroeste",
  "El Conejo Viejo",
  "El Carrizalito",
  "Las Castellanas",
  "El Chilerito [Agrícola]",
  "El Chapil",
  "La Cieneguita de Guadalupe",
  "El Comitán",
  "Las Coras Tal Mar",
  "El Corral de Piedra",
  "Los Corralitos",
  "La Cruz",
  "Los Cuatro Hermanos",
  "El Cuave",
  "Dos Arbolitos",
  "Las Dos Palmas",
  "Los Escavaderos",
  "La Estaca",
  "El Galerón",
  "El Gaspareño",
  "San Miguel [Granja]",
  "El Grullo",
  "El Cenizo",
  "Los Guayabitos",
  "La Higuerita",
  "Los Horconcitos",
  "El Huérivo",
  "José de Jesús Figueroa",
  "Ley Federal de Reforma Agraria No. 2",
  "Ley Federal de Reforma Agraria Número Uno",
  "El Llano",
  "Los Llanos",
  "La Virgencita",
  "Rancho Lourdes",
  "Manzanillo",
  "Mendieta Bueno",
  "La Natividad",
  "Las Pacas",
  "Palo la Blancosa",
  "El Palacio",
  "Las Parritas",
  "Puerto de Pichilingue",
  "La Piedra",
  "Los Potrerillos",
  "La Laguna del Rifle",
  "Punta Coyote",
  "Punta Pescadero",
  "Punta Prieta",
  "La Raizuda",
  "Agrodelicias de la Baja Sur",
  "El Rosario",
  "El Sacrificio",
  "El Salado",
  "El Saltito",
  "Salto de los Reyes",
  "San Antonio [Lonchería]",
  "Agua de San Antonio",
  "San Felipe de las Playitas",
  "San Isidro de las Palmas",
  "El Bosque de San Isidro",
  "Las Pilas",
  "San Juan del Aserradero",
  "San Juan del Rancho",
  "San Pedro de la Soledad",
  "San Pedro el Frijolar",
  "San Rafael",
  "San Salvador",
  "Santa Teresita",
  "Los Quijote",
  "Santa Gertrudis",
  "Santa Martha",
  "Santa Teresa de la Soledad",
  "Santa Victoria",
  "El Sargento",
  "Los Sauces",
  "El Bosque",
  "Las Tablitas",
  "El Tecuán",
  "Bernardino",
  "Los Dos Hermanos (El Zorillo)",
  "San Marcos (La Ayuquita)",
  "Zacatecas",
  "La Cueva",
  "Los Dolores",
  "Humí",
  "Las Parcelas",
  "Punta Alta",
  "El Agua de Yepis",
  "San Francisco de la Costa",
  "Canta Rana",
  "La Capilla",
  "El Caporal",
  "El Chamizal",
  "Iraquí",
  "El Paso de Encinas",
  "La Presa de Guadalupe",
  "Punta del Cerro",
  "El Sauce",
  "Las Tinajas de Orantes",
  "Las Tinajitas",
  "Santa María de Toris",
  "La Bolsa del Toro",
  "Agüí Viejo",
  "El Merecuaco",
  "La Redención",
  "San Cayetano del Ciruelo",
  "Saucito del Cedro",
  "A Dónde",
  "El Ademado",
  "Aguaje de San Vicente",
  "Los Alamitos",
  "Las Albóndigas",
  "Los Altares",
  "El Aparejo",
  "El Arroyo del Diablo",
  "El Arroyo del Novillo",
  "El Barranco",
  "El Batequito",
  "El Califín",
  "Las Canoas",
  "Cañada de la Huerta",
  "Piedras Coloradas",
  "Los Cerritos",
  "El Chaparral",
  "El Milagro",
  "Colonia Campestre del Periodista",
  "El Corral de las Choyas",
  "El Crestón",
  "El Dorado",
  "Los Dos Amigos",
  "El Vergel",
  "Ejido San Luis",
  "El Fundador",
  "La Encina",
  "El Estribo",
  "Forestal",
  "El Gavilán",
  "El Retiro [Granja]",
  "Rancho Guadalupe",
  "Hierba del Manzo",
  "La Huertita",
  "Las Higueritas",
  "El Rinconcito",
  "Jesús María",
  "Santa María (El Juyateve)",
  "Lupita [Lonchería]",
  "El Magueyal",
  "Mar Azul (San Patricio)",
  "La Puerta",
  "La Mesa del Encino",
  "La Mesa del Molino",
  "El Mezcalito",
  "El Mezquital",
  "El Mezquitón",
  "Miramar",
  "Moscú",
  "El Negrito",
  "El Novillo",
  "Olas Altas",
  "El Orégano",
  "El Otro Arroyo",
  "El Parral",
  "La Palmita",
  "San José",
  "Las Dos Palomas",
  "El Paraje",
  "La Pastora",
  "La Piedra Larga",
  "Las Piedras Moras",
  "El Plan del Paso",
  "La Ponderosa",
  "La Poza Verde",
  "Los Queleles",
  "El Calandrio",
  "El Mayela",
  "El Capricho",
  "San Alfonso",
  "El Sinaloa",
  "La Rastrita",
  "Miriam [Restaurante]",
  "El Rodeíto",
  "Salinas Punta Arena",
  "San Agustín",
  "San Cristóbal",
  "San José del Parral",
  "San Juanito",
  "San Martín de la Redención",
  "San Rafael del Pilar",
  "Tiluya",
  "Santa Mónica",
  "El Taray",
  "La Pimientilla",
  "Las Tunitas",
  "La Uva",
  "Las Uvas",
  "El Venero",
  "Las Veredas",
  "Vista Cerralvo",
  "Las Palomas (San Blás)",
  "El Partido",
  "La Palma Sola",
  "Puerto Dátil",
  "Rancho Nuevo",
  "Los Arbolitos",
  "Las Golondrinas",
  "El Cuernavaca",
  "El Capiro",
  "El Carmen",
  "El Cinco",
  "El Cachanilla",
  "El Albatros",
  "Los Naranjos",
  "Los Columpios",
  "Los Faustos",
  "Los Guayabos",
  "Las Cuevas",
  "El Orgullo",
  "El Escondido",
  "El Cielito",
  "El Cajón de los Reyes",
  "El Cananea",
  "Grupo 10",
  "Boca del Datilar",
  "El Quemado",
  "La Manca",
  "El Yorigeobe",
  "El Cajón",
  "Los Mezquites",
  "El Salveal",
  "Los Nogales",
  "Las Vinoramitas",
  "Punta Ballena",
  "Los Vergelitos",
  "El Arroyo del Gato",
  "Las Brumas",
  "La Florida",
  "Ex-Hacienda el Centenario",
  "El Ojeda",
  "El Scirocco",
  "Las Parcelas Dos",
  "El Zacatal (La Cartonera)",
  "El Bethel",
  "Los Bledales",
  "Santa Eduwiges",
  "El Oká",
  "Ninguno",
  "El Sufrido",
  "Laguna Seca [Fraccionamiento]",
  "Paraje los Chinos",
  "Los Angelitos (Palo Verde)",
  "San Fermín de Abajo",
  "Grupo 3",
  "Los Dos Baynoros",
  "Las Palomas",
  "La Piedrita",
  "Rancho Camacho",
  "San Luisito",
  "El Cachania",
  "El Mautalito",
  "Rancho Mora",
  "San Carlos Tercero",
  "Guadalupe y Mangle",
  "Santa Rosa de los Pinos",
  "San Diego",
  "El Winolito",
  "El Agua Tapada",
  "Campo Pesquero",
  "El Pardito",
  "Tabampo",
  "El Aeropuerto",
  "Agua de la Palma",
  "El Agua Escondida",
  "Dos de Abril (Las Amazonas)",
  "Los Arados",
  "La Bajada del León",
  "La Ballena",
  "Las Bugambilias",
  "Callejón 3 Palmas",
  "Todos Santos [Campo Experimental]",
  "El Triunfito",
  "Tortuga del Sol",
  "Cañada la Leña",
  "Campestre el Mezquitito",
  "El Carrizal [Centro de Propagación Vegetal]",
  "El Choyal",
  "El Ciruelo Muñoz",
  "El Carrizal [Club Campestre]",
  "Coral de las Playitas",
  "Ejido San Vicente Grupo 2",
  "Ejido San Vicente Grupo 8-A",
  "Tres Palmas (Ejido San Vicente)",
  "El Girasol",
  "La Barca",
  "La Fundición",
  "Los Hermanos Ford",
  "La Rueda",
  "El Huatamotito",
  "Los Jiménez",
  "El Nueve",
  "Lomita Amarilla",
  "El Alteño",
  "Las Palmitas",
  "Piedras Moras",
  "El Pinito",
  "La Pitayosa",
  "Playa el Tesoro",
  "Ninguno [Vivero]",
  "El Pulguero",
  "Punta Pelícanos",
  "El Setentaidós",
  "Unidad Pichilingue de la UABCS",
  "Citlalli",
  "Rancho de Avilés",
  "El Duarte",
  "La Higuera",
  "Rancho Gem",
  "Don Nacho",
  "El Maniadero",
  "El Molino",
  "El Palomo",
  "Rancho del Mar",
  "Chulavista",
  "La Caridad",
  "Los Bledales (La Ceibita)",
  "La Colmena",
  "La Noria",
  "La Noria Lote 3",
  "La Pajarilla",
  "Los Migueles",
  "San Isidro de la Campana",
  "Rancho Orgánico California",
  "Jaibolito",
  "Darinka",
  "Kilómetro 45",
  "El Rincón",
  "Dos de Abril (El Rodeo)",
  "San Ignacio de las Playitas",
  "San José del Quelele",
  "San Juanito Nuevo",
  "Encino",
  "San Miguel del Triángulo",
  "Ninguno [Manuel Avilés]",
  "Santa Genoveva",
  "Santa Rosita de Lima",
  "La Palapa",
  "El Paraíso",
  "Boca de la Muela",
  "Tierra Santa",
  "Ninguno [Emilio Yarel]",
  "Tepescala",
  "El Mezquitito",
  "Las Auroras",
  "Mi Propiedad",
  "La Dispensa",
  "El Gallo",
  "La Gloria",
  "Los Huérivos",
  "El Huizache",
  "La Ilusión",
  "Las Minas",
  "La Mojonera",
  "Las Norias (Las Palmas)",
  "Punta el León",
  "La Purga",
  "Quinta Yea",
  "El Copal",
  "El Mocorito",
  "Rancho Roxana",
  "El Salto de Bair",
  "San Jorge del Rinconcito",
  "Palo Blanco",
  "El Portugués",
  "Kilómetro 91",
  "Colonia 28 de Octubre (Kilómetro 6)",
  "Demasías de los Bledales",
  "Empresas Longoria",
  "San Benito",
  "San Blás Lote 7",
  "Diana [Mini Súper]",
  "Valle Dorado",
  "Rancho Verde",
  "Perla Azul",
  "Chekos [Minisúper]",
  "Las Palmeras",
  "Almacén General Compañía Batis",
  "Ninguno [Almacén y Molino Forrajero]",
  "Ninguno [COPLAMAR]",
  "La Joya del Mar [Empacadora]",
  "San Miguel el Grande",
  "Kilómetro 44",
  "El Salitral",
  "Laguna Seca",
  "Los Tesitos",
  "Los Juanitos",
  "El Wamerú",
  "La Ceiba",
  "Demasias de la Matanza",
  "El Ancón de Julio",
  "La Aplanada",
  "Boca del Refugio",
  "Ninguno [Campo Experimental de Energía Solar]",
  "Las Gatas",
  "La Irolina",
  "El Palmar de la Matanza",
  "La Piedra Gorda",
  "Rancho Margarita",
  "Oasis del Desierto (La Criba)",
  "Santa Bárbara",
  "La Buena Suerte",
  "Los San Juanes",
  "El Zorrillo",
  "Bahía Turquesa",
  "La Ballena de los Inocentes",
  "Brisas del Mar",
  "Las Cabras",
  "Los Cascabeles",
  "La Chacuaca",
  "Agrícola Ángel del Norte",
  "El Crucero de Milano",
  "Las Cuatro Milpas",
  "El Descanso",
  "Los Dos Hermanos",
  "El Empachado",
  "El Encadenado",
  "La Huerta Escondida",
  "El Frijolar",
  "Los Gatos",
  "El Gorrión",
  "El Desmonte",
  "Rancho Choix",
  "El Muro",
  "El Palo Adán",
  "Paloma Blanca",
  "La Parcela",
  "Los Patos",
  "Playa el Tecolote",
  "Quinta Santa Elena",
  "Santa Elena del Quelele",
  "San Julián",
  "La Ladrillera",
  "Santa Regina",
  "El Vaso",
  "El Otatave",
  "Chula Vista",
  "La Fuente de Marbella",
  "Los Pinos",
  "La Alegría",
  "Las Flores Dos",
  "El Manantial",
  "Rancho el Gordo",
  "El Paso del Tepetate",
  "El Country",
  "El Zalate de Arriba",
  "La Tinajita",
  "San Pedro [Granja]",
  "El Sol",
  "La Cuchara",
  "San Silvestre",
  "Familia Simental Vargas",
  "Los Tres Potrillos",
  "Familia Guadalupe Loya",
  "Las Dos Marías",
  "El Paso de Iritú",
  "Rincón San Guillermo",
  "Las Dos Luces",
  "Chayito [Mini Súper]",
  "El Calorón",
  "El Jalito",
  "El Cajete",
  "La Duna",
  "El Paso",
  "San Alberto",
  "Felipes [Restaurante]",
  "La Puerta Azul",
  "Campamento Agrícola del Mar",
  "Piedras Negras",
  "La Angostura",
  "La Bajada Verde",
  "La Huerta del Potrero",
  "Punta Colorada",
  "La Santa Cruz",
  "Brisas del Desierto [Restaurante]",
  "Santa María de Guadalupe",
  "Las Flechas",
  "Cerro del Toro",
  "Los Derramaderos",
  "Balandra",
  "Las Palmas de San Lorenzo",
  "San Agapito",
  "Las Cuatro",
  "La Terquedad",
  "El Palvadán",
  "La Libra",
  "El Naranjo",
  "El Copalquín",
  "Santa Lidia [Agrícola]",
  "El Maguey",
  "Puerta Dorada",
  "Altamira",
  "Santa Elena",
  "La Herradura",
  "El Cañón de la Brecha",
  "Granjas Familiares la Paz",
  "Las Maravillas",
  "La Petaca",
  "La Venta",
  "El Fresno",
  "Frutería y Dulcería Otatave",
  "Lonchería Daniel",
  "El Arroyo del Diablo Dos",
  "El Manchón",
  "La Ballenita",
  "La Biznaga",
  "La Pila",
  "Las Cuatro Lupitas",
  "Los Cuates",
  "Maravia",
  "Vista Hermosa",
  "El Pila",
  "Arroyo Hondo",
  "Rosa Linda [Lonchería]",
  "Chametla Grupo Ocho",
  "La Mina Negra",
  "Las Palmillas",
  "El Bajío (Las Isabeles)",
  "El RC",
  "San Felipe",
  "León [Abarrotes]",
  "González [Ultramarinos]",
  "Carolina (Agua Nueva)",
  "Baja Dogs",
  "Cañada Honda Grupo 33",
  "El Cayuri",
  "El Cerro de Oro",
  "Colonia Primero de Mayo",
  "La Cruz de Piedra",
  "El Barrial",
  "El Breñal",
  "El Cárdenas",
  "El Derramadero",
  "El Hermes",
  "El José María",
  "El Junco",
  "El Merecuaco Dos",
  "El Olvido",
  "El Oroche",
  "El Pacífico",
  "El Palo Blanco",
  "El Reparito",
  "El Sauzal",
  "El Tunalito",
  "El Vuelo del Águila",
  "El Emmanuel",
  "La Tierra Noble",
  "Granjeros Guaycura",
  "El Sureño [Granja Camaronera]",
  "Kilómetro 107",
  "Kilómetro 109",
  "La Brecha",
  "La Criba",
  "La Fusca",
  "El Centenario [Granja]",
  "La Lagunita",
  "La Palmita Dos",
  "La Salinita",
  "La Subida",
  "Las Tres A",
  "Las Anitas",
  "Las Piedras",
  "Las Tres Hermanas",
  "Los Juncos",
  "Los Magallones",
  "Los Potrillos",
  "Los Sauzones",
  "Los Tres Brasiles",
  "Los Tres Reyes",
  "Mesa de la Carrera",
  "San Antonio [Minisúper]",
  "Punta de los Muertos",
  "El Alcantar",
  "Rancho Chico",
  "La Guadalupana",
  "Familia Rosita González",
  "Revolcadero de las Liebres",
  "San Antonio del Quemado",
  "San Bartolito",
  "San Gregorio",
  "San Juan de Arriba Tours",
  "San Juan del Aguajito",
  "San Judas Tadeo",
  "San Pablito",
  "Santa Emma",
  "Santa María de Magdalena",
  "La Siempre Vive",
  "La Subida de la Palmita",
  "Tierra Noble",
  "Campestre el Cardón [Fraccionamiento]",
  "Lomas del Cardón [Fraccionamiento]",
  "El Acero [Recicladora]",
  "El Volver",
  "La Flecha de los Marrón",
  "Los Paraísos",
  "Monteverde [Ladrillera]",
  "La Ponde",
  "El Amadeo",
  "El Paraíso de José Luis",
  "Los Talamantes",
  "Rancho de José",
  "La Montaña",
  "El Mumú",
  "Las Tres Estrellas",
  "Gabriel León Villarina",
  "El Cardoncito",
  "Rancho Maricruz",
  "Cachimba",
  "Carolina",
  "Margarita Maza de Juárez [Escuela]",
  "Culiacán (La Trinchera)",
  "Ejido San Vicente Grupo 1",
  "El Calisón",
  "El Cazón",
  "El Ciruelito II",
  "El Guamuchilón",
  "El Güirote",
  "El Higuajil",
  "El Macapule",
  "El Mapache Solitario",
  "El Mejorcito",
  "El Palmarito II",
  "El Palmira",
  "El Potro Solo",
  "El Tunalito Dos",
  "El Venado [Grúas]",
  "La Damiana",
  "Laguna del Venado",
  "La Marroneña",
  "Shureyas",
  "Las Casitas",
  "Las Isabeles",
  "Las Lomas",
  "Las Manitas",
  "La Mesa Alta",
  "Los Dos Santitos",
  "Monte Sereno",
  "José Antonio Sánchez Cosió",
  "Agrícola Brajama",
  "Ninguno [Constructora]",
  "Novillos y Coras",
  "Nuevo Amanecer",
  "Puertecitos",
  "Rancho de Moreno",
  "Rancho Seco",
  "Rancho Viejo",
  "Real de Palmas",
  "San Antonio de la Cruz",
  "San José de las Tinajitas",
  "San Judas",
  "San Valentín",
  "Santiago del Alto",
  "Tierra Blanca",
  "San Isidro de las Playitas",
  "La Criba de los Tesitos",
  "Ampliación de la Matanza",
  "La Cañada",
  "Copales",
  "El Gacho",
  "Jesús Florencio Polo Murillo",
  "Kilómetro 80",
  "La Bajadita",
  "Pozo la Noria",
  "Brisamar",
  "La Palobrea",
  "Rancho Teresita",
  "Vista los Paredones",
  "San Antonio (Kilómetro 45)",
  "San Francisco de Asís",
  "San Nicolás",
  "Santa Rana",
  "Tierra Generosa [Vivero]",
  "La Savila",
  "El Anhelo",
  "Los Agaves",
  "Rancho Don Gelasio",
  "Los Lucero",
  "Juan Simón Pedro",
  "San Antonio del Cuadradito",
  "El Sotol",
  "Cerro Pelón",
  "El Perro Despreciado",
  "Mata Grande",
  "Cactimar",
  "Ninguno [La Extranjera]",
  "Los Venados",
  "Huertas del Manantial",
  "Ninguno [Antonio Prieto Prieto]",
  "Ninguno [Homero Ceseña]",
  "Misión Trinidad",
  "Milagros",
  "Ninguno [Casa del Barrita]",
  "El Mautito",
  "El Teporocho",
  "Pénjamo",
  "El Huizapol",
  "Salvatierra",
  "El Viejo Amor",
  "Tres Ángeles",
  "La Tinaja",
  "Las Malvinas",
  "Santo Domingo de en Medio",
  "Kilómetros 65",
  "Hong Kong",
  "Artejal",
  "Palo San Juan",
  "Santo Domingo Dos",
  "Santa Teresita de Arriba",
  "Las Tunas",
  "Juana Villalobos",
  "Palo Fierro",
  "Cañada de Palo Verde",
  "La Mora",
  "Quintas Delfín",
  "San Francisco",
  "La Querella",
  "Yepiz",
  "La Ciénega",
  "Jorge Luis",
  "El Remanso",
  "El Paso del Águila",
  "San Juditas Tadeo",
  "Santa Viviana",
  "Rancho MCV",
  "Esmeralda",
  "Cristo Vive",
  "El Cero",
  "San Juditas",
  "El Obispo",
  "Kilómetro 140",
  "Kilómetro 129",
  "La Charrasqueada",
  "Primavera [Fraccionamiento]",
  "Campo APR",
  "La Tormenta (Los Alazanes)",
  "El Sacrificio Dos",
  "Los Márquez",
  "La Piedrecita",
  "Rancho Escondido",
  "Bonanza Cubilete",
  "Kilómetro 95",
  "El Espíritu",
  "Los Coyotes",
  "Cuesta Blanca",
  "Jesús María del Cardonete",
  "Piedra Rodada",
  "El Puerto",
  "San Blas",
  "La Loma",
  "San Pedrito",
  "Aurelio Morales"
]