export const LoretoTownshipTowns = [
  "Loreto",
  "La Tinaja del Caracol",
  "Aguajitos",
  "La Ascensión",
  "Las Bebelamas",
  "Canipolé",
  "El Cardonal",
  "El Imposible",
  "Lote 42",
  "Lote 2-A",
  "La Giganta",
  "Lote 9-A",
  "Lote 11",
  "Lote 3-A",
  "Lote 1",
  "Lote 25",
  "Lote 26",
  "El Manglito",
  "El Molino",
  "Monte Cabello",
  "Naocojoa",
  "Pénjamo",
  "La Piedra",
  "El Pozo Redondo",
  "El 47",
  "El Cimarrón",
  "Rentoy",
  "San Antonio",
  "San Juan",
  "Lote 67",
  "San Juan Londó",
  "San Nicolás",
  "San Pedro",
  "San Vicente",
  "Santa Rosa",
  "El Saucito",
  "El Troquero",
  "Rancho Nuevo (La Casa Vieja)",
  "El Pozo",
  "La Calera",
  "Chula Vista",
  "Los Encinos",
  "Monte Alto",
  "Rancho Viejo",
  "San Francisco de Asís",
  "San Guillermo",
  "Santa Isabel",
  "Los Aguajitos",
  "Lomas Altas",
  "Lomas Lindas",
  "Nopoló",
  "Las Parras",
  "Las Piedras Rodadas",
  "La Mesa",
  "El Rincón",
  "San Felipe",
  "La Venta",
  "Agua Amarga",
  "El Agua Bonita",
  "Agua Escondida",
  "El Aguaje",
  "La Altagracia",
  "La Angostura",
  "El Carrizalito",
  "Los Corrales",
  "La Cruz",
  "El Divisadero",
  "El Edén",
  "La Engañosa",
  "Ensenada Blanca",
  "La Higuera",
  "El Huatamote",
  "Ligüí",
  "El Mezquite",
  "El Palo Blanco",
  "El Peloteado",
  "La Poza de González",
  "La Poza de Teresa",
  "La Poza Seca",
  "La Poza Verde",
  "Puerto Escondido",
  "San Enrique",
  "San Lorenzo",
  "San Lucas",
  "Santo Domingo",
  "El Corralito",
  "Tripuí [Trailer Park]",
  "La Vuelta del Cerro",
  "El Belén",
  "Las Cuevas",
  "Los Dolores",
  "La Fortuna",
  "Los Hornos",
  "Inchá",
  "Juncalito",
  "Rancho Nuevo Dos",
  "El Púa",
  "Rancho Nuevo",
  "San Javier",
  "San Ramón",
  "Santa María",
  "El Segundo Paso",
  "Tiombó",
  "Agua Verde",
  "Los Sestiaderos",
  "El Paso de Santa Cruz",
  "La Presa",
  "Puerto Agua Verde",
  "San Antonio de la Higuera",
  "Santa Cruz",
  "Santa Martha",
  "El Tulillo",
  "La Última Agua",
  "San Carlos",
  "Timbabichi",
  "Isla Nuestra Señora del Carmen",
  "Santa Inés",
  "Las Brisas",
  "Buenavista",
  "El Arroyo del León",
  "Jacobo",
  "Lote 9-B",
  "Lote 60",
  "La Morena",
  "Palo Blanco",
  "El Pasito",
  "Rancho San Cosme",
  "Uña de Gato",
  "Arroyo de Parras",
  "Los Bajos",
  "El Campo Blanco",
  "Los Búfalos",
  "Hacienda Guadalupe",
  "El Palmarcito",
  "San Ángel",
  "El Copalito",
  "Las Pozas",
  "El Sacrificio",
  "Danzante Bay",
  "El Entronque de Agua Verde",
  "Rancho Guadalupe",
  "Ejido Loreto al Sur",
  "Lupita [Restaurante]",
  "San Bruno",
  "La Soledad",
  "Rancho la Chingada",
  "El Paso Colorado",
  "Las Huertas",
  "La Vinatería",
  "La Piedra Rayada",
  "La Herradura",
  "La Ilusión",
  "La Pila",
  "La Virgencita",
  "Las Palmas",
  "Los Cachorones",
  "Los Mangles",
  "Los Palos Fierros",
  "Los Seris",
  "Los Mangos",
  "Rancho Escondido",
  "Notri",
  "San Basilio",
  "San Juaniquito",
  "Agua Amarga Dos",
  "Huatamote Viejo",
  "San Ignacio",
  "Cadejé",
  "La Ardilla",
  "El Puertito",
  "Los Tres Chamacos",
  "San Cosme",
  "Los Corrales Dos",
  "El Mauto",
  "San Gregorio",
  "La Envidia",
  "Los Dos Hermanos",
  "Rancho San Judas",
  "Rancho Buenavista",
  "El Cinco",
  "La Cúpula",
  "Álamo",
  "La Pitaya",
  "Punta Ballena",
  "El Bajo",
  "La Higuerita",
  "Tecoragui"
]