export const LosCabosTownshipTowns = [
  "San José del Cabo",
  "El Agua Azul",
  "Agua Caliente",
  "El Agua de Juan",
  "Agua Escondida",
  "Los Aguajitos",
  "El Álamo",
  "Los Algodones",
  "Los Ancones",
  "El Anhelo",
  "Antares",
  "Demasías de San Luis",
  "El Aserradero",
  "La Ballena",
  "Las Barracas",
  "El Barranco",
  "El Barrito Dos",
  "Boca de la Sierra",
  "Boca de los Tesos",
  "Boca del Salado",
  "Boca de San Cristóbal",
  "Boca de la Vinorama",
  "Buenavista",
  "El Cabello",
  "Cabo Pulmo",
  "Cabo San Lucas",
  "Las Cabras",
  "Caduaño",
  "El Cajón de Yéneka",
  "La Calabaza",
  "La Candelaria",
  "El Cantil",
  "El Cardonal",
  "El Carrizalito",
  "Las Casitas",
  "Cerro Prieto",
  "La Cieneguita",
  "El Conejo",
  "El Copalar",
  "Coral de Frailes",
  "Corral Viejo",
  "El Cajón de los Reyes",
  "Las Cuevas",
  "El Chinal",
  "El Chuchupate",
  "El Datilar",
  "Las Delicias",
  "El Deshecho Dos",
  "El Encinalito",
  "Los Encinitos",
  "El Encino Gordo",
  "El Epazote",
  "La Fortuna",
  "Los Frailes",
  "El Garambullo",
  "Los Guayacanes",
  "El Guayparín",
  "La Joya",
  "La Lengua de Buey",
  "La Línea",
  "El Machete",
  "El Mauto",
  "El Mangle",
  "El Mezquite",
  "Miraflores",
  "Las Norias",
  "Las Palmas",
  "La Palmilla",
  "Palo Escopeta",
  "Palo Verdal",
  "Panamá",
  "Las Parras",
  "Las Piedras",
  "El Pilar Uno",
  "Migriño",
  "El Pozo de Cota",
  "Los Pozos",
  "El Ranchito",
  "Rancho Nuevo",
  "El Refugio Uno",
  "La Ribera",
  "El Rosarito",
  "El Salado Viejo",
  "El Salteador",
  "El Salto de Gavaráin",
  "San Agustín",
  "San Alberto",
  "San Antonio",
  "San Dionisio",
  "San Julio",
  "Barrio de San Isidro",
  "San Jorge",
  "San Juan",
  "San Marcos",
  "San Miguelito",
  "San Nicolás",
  "San Pedro",
  "San Ramón",
  "Santa Águeda",
  "Santa Catarina",
  "Santa Cruz de los Zacatitos",
  "Santa Elena",
  "Santa Rita",
  "Santa Victoria",
  "Santiago",
  "San Venancio",
  "El Saucito",
  "El Sauzal",
  "La Soledad",
  "El Torote",
  "La Trinidad",
  "Las Veredas",
  "La Vinatería",
  "La Vinorama",
  "El Zacatal",
  "El Zacatón",
  "Agua Escondida de Arriba",
  "El Leonero",
  "La Capilla",
  "Los Corrales",
  "El Coyote",
  "Cuesta de León",
  "La Cuesta de la Palma",
  "Las Chiveras",
  "La Matagorda",
  "Matancitas",
  "El Mezcal",
  "Las Milpillas",
  "La Misión",
  "Los Naranjos",
  "La Palma",
  "La Palmita",
  "El Rancho",
  "El Rincón de San Pedro",
  "El Romerillal",
  "Santa Teresita",
  "Siempre Viva",
  "El Surgidero",
  "El Agua Fría",
  "Agua Hedionda",
  "El Aguajito",
  "Los Alamitos",
  "Altamira",
  "La Ascensión",
  "El Barranquito",
  "La Burrera",
  "La Boca de la Palma",
  "Boca del Tule (Villas del Faro)",
  "El Calientito",
  "El Cardón",
  "Casas Viejas",
  "Los Ceniceros",
  "Cerro Colorado",
  "Chapultepéc",
  "El Chicural",
  "El Chorro",
  "El Corral de Piedra",
  "El Corral Falso",
  "Cuentascuávil de Abajo",
  "Las Dos Ballenas",
  "El Encinal",
  "El Encino",
  "El Guamuchilar",
  "Los Guayabos",
  "Yéneka",
  "El Escopetal",
  "La Junta",
  "La Otra Agua",
  "La Matancita",
  "El Moro",
  "Palmilla",
  "La Palmilla del Pacífico",
  "La Palmilla de San Felipe",
  "El Parralito",
  "Las Parritas",
  "El Portezuelo",
  "La Poza Verde",
  "Las Presas",
  "La Ramadita",
  "El Refugito",
  "La Querencia",
  "El Saltito",
  "El Rodeo",
  "El Salto Tendido",
  "El Salto",
  "San Carlos",
  "San Felipe",
  "San Ignacio",
  "Rincón de San Lázaro",
  "Los Llanos del Guajal",
  "San Román",
  "Santa Amalia",
  "Santa Cruz",
  "Santa María",
  "Los Tesos",
  "El Tetinal",
  "Las Vinoramas",
  "El Zorrillo",
  "San Miguel",
  "La Cañada de Enmedio",
  "Cabo Vinorama Estates",
  "El Ancón Largo",
  "El Ancón Verde",
  "Boca de Margarita",
  "El Cajón",
  "El Cajoncito",
  "La Piedad",
  "El Chapuli",
  "Rancho Escondido",
  "Guadalajara",
  "La Jolla",
  "La Laguna",
  "Lagunitas de los Frailes",
  "La Ley del Monte",
  "Los Mártires",
  "El Mezquital",
  "El Otro Arroyo",
  "La Palmillita",
  "Palo Verde",
  "El Paúl",
  "Piedras Bolas",
  "Los Pinos",
  "Plan de los Dos",
  "El Salomo",
  "San Alfredo",
  "San Javier",
  "San Lázaro",
  "El Refugio (San Martín)",
  "San Ramoncito",
  "Santa Bárbara",
  "Las Termópilas",
  "Las Tinas",
  "La Ventanita",
  "San Pablo",
  "Sestiadero de la Trinidad",
  "El Sueño",
  "La Parada",
  "Agua del Llano",
  "Las Manzanas",
  "Las Gardenias",
  "Los Brincos",
  "El Campamento",
  "Casa Vieja",
  "La Barrosa",
  "El Agua de la Palma",
  "Santa Anita",
  "San Gabriel",
  "Boca de la Trinidad",
  "Rancho Don Martín",
  "Casa Gleen",
  "El Mocorito",
  "El Tezal",
  "Colonia María Sandéz Viuda de González",
  "El Intermedio",
  "La Cuchilla Alta",
  "El Chulo",
  "El Agua de Abajo",
  "Agua Escondida de Abajo",
  "Agua Verde",
  "Los Álamos",
  "Almacén Forrajero",
  "El Ancón Grande",
  "Arroyo Hondo",
  "El Carrizal",
  "El Juguete [Cervecería]",
  "El Chacuaco",
  "El Chaparral",
  "Los Chilpitines",
  "La Chiquita",
  "El Corralito",
  "El Crucero de Miraflores",
  "El Desecho Uno",
  "El Encino Gacho",
  "El Garachito",
  "La Gloria",
  "Punta Colorada [Hotel]",
  "Huerta Verde",
  "Las Huertas",
  "La Ilusión",
  "Los Laureles",
  "Palapa Fisher",
  "El Palo de Arco",
  "El Palo Escopeta",
  "El Palo Verde",
  "Las Pilas",
  "Las Anastasias",
  "Playa Tortuga",
  "El Progreso",
  "Punta Arena",
  "Rancho Escondido del Salto",
  "Rancho Viejo",
  "El Refugio",
  "Migriño [Restaurante]",
  "El Rincón",
  "El Salto Carrizo",
  "San Antonio de las Huertas",
  "San Cirilo",
  "San Diego",
  "San José",
  "San Juan Dos",
  "San Martín de los Llanitos",
  "Santa Cornelia",
  "Santa Gertrudis",
  "Santa Mónica",
  "El Tucán",
  "Las Tachuelas",
  "La Tuna",
  "La Malteada",
  "El Lobo",
  "Las Praderas",
  "La Dorada",
  "La Angostura",
  "Buenos Aires",
  "La Cabaña",
  "Chametla",
  "El Cortijo",
  "La Pimientilla",
  "San Jorge 3",
  "La Torre",
  "La Abeja Reyna del Cabo",
  "Ninguno [Almacén Comunitario]",
  "Rancho Viejo [Restaurante]",
  "Ninguno [Cabo Gas]",
  "Colonia Valtierra",
  "La Huerta",
  "San Luis",
  "La Acacia",
  "El Barrito Uno",
  "Los Cascabeles",
  "Costa de Oro",
  "El Delirio",
  "Los Gavilanes",
  "Las Huertitas",
  "El Magueyal",
  "Pindoco",
  "El Paso",
  "Punta Paredones",
  "Ninguno",
  "La Verdad",
  "El Vinoramal",
  "El Pozo de Arámburo",
  "Las Guacamayas",
  "El Güérivo",
  "Las Lagunillas",
  "San Bernardo Seis Hermanos",
  "El Tío Juan",
  "Los Vergelitos",
  "El Guaje",
  "El Bacote",
  "El Castillo de Arena",
  "Cuadra San Francisco",
  "Santa Martha [Granja]",
  "El Gran Chaparral",
  "Camino a San Felipe",
  "Rosarito",
  "San Bernabé",
  "Villa las Dunas",
  "Tropical [Vivero]",
  "La Viga",
  "Cactus [Vivero]",
  "El Norber",
  "La Lagunilla",
  "Agüita Escondida",
  "La Esperanza",
  "Barrio Boca de la Cañada",
  "El Trópico de Cáncer",
  "La Machaca",
  "Ligth House Point States",
  "La Almeja",
  "El Guamúchil",
  "La Sabanilla",
  "El Cantilito",
  "El Capricho",
  "Kilómetro 88",
  "La Limonada",
  "San Juan de los Lagos",
  "El Agua de Roque",
  "Los Arbolitos",
  "El Barrilito",
  "Las Tejas",
  "Los Marios",
  "Macapul",
  "El Propósito",
  "El Toruno",
  "La Victoria",
  "Las Casitas de Arriba",
  "San Bernardo",
  "Santo Domingo",
  "San Valentín",
  "Cerro de los Chivos",
  "Huerta la Noria",
  "El Encanto",
  "Tierrita Blanca",
  "El Centauro [Granja]",
  "El Chinal Viejo",
  "La Escondida",
  "Vianey [Restaurante]",
  "Plata Perdida",
  "El Agua del Coyote",
  "Lo Quemado",
  "Bahía Terranova",
  "Vinoramas Diamante",
  "Cactus ATV",
  "El Cascabel",
  "Castillo San Simón",
  "Ninguno [Cementos Gusa]",
  "Ninguno [Cementos PMC]",
  "Ninguno [CERESO]",
  "Las Abejas",
  "Mi Princesa",
  "Colonia las Tres Palmas",
  "Corrales de Rosendo",
  "Ninguno [Corralón Vehicular Ayuntamiento]",
  "El Brasil",
  "Espíritu Santo",
  "El Lachón",
  "El Paraíso",
  "El Pilar Dos",
  "El Refugio de las Águilas",
  "El Rinconcito",
  "El Salto de Arriba",
  "La Herradura",
  "Loma Linda",
  "La Mina",
  "La Otra Loma",
  "La Pradera",
  "La Sabania Uno",
  "La Sabania Dos",
  "Las Flores",
  "El Agua de Paloma",
  "San Roque",
  "Rancho Doña Martha",
  "La Huertita",
  "Los Tres Hermanos",
  "Los Ciruelos",
  "Los Compadres",
  "Los Delfines",
  "Los Morritos",
  "Maracano",
  "La Mesa Blanca",
  "Mi Viejo San Juan",
  "Migriño Hacienda",
  "El Potrerito",
  "El Arroyo Seco",
  "Los Cuatro Hermanos",
  "Rancho de la Sierra",
  "Don Pepe",
  "El Cantador",
  "El Deseo",
  "El Enfado",
  "El Escorpión",
  "El Paraje",
  "El Picho",
  "El Zapotillo",
  "La Sierrita",
  "Las Rosas",
  "Los Carnales",
  "Los Cerritos",
  "Los García",
  "Los Plebes",
  "Los Santos",
  "San Francisco",
  "Santa Eugenia",
  "El Mexicano",
  "El Toro Muerto",
  "Ninguno [Rastro TIF]",
  "Rollin Hills [Hotel]",
  "San Ángel",
  "San Antonio de Padua",
  "San Gerardo",
  "San Luis Dos",
  "Santa Rosa",
  "Sol de Mayo",
  "El Suspiro",
  "La Comunidad",
  "Los Llanitos",
  "Los Tomates",
  "El Palo Amarillo",
  "El Halcón",
  "Familia José Ramón",
  "Los Mezquites",
  "Los Ramírez",
  "Cuatro Estaciones",
  "El Mestizo",
  "Granja la Herradura",
  "Las Bugambilias",
  "El Porvenir",
  "Palo Blanco",
  "Los Rosales",
  "Lomas del Encino [Granjas]",
  "Los Tres Amigos [Huerta]",
  "La Cuadra Regina",
  "La Jungla Cactus [Vivero]",
  "San Lorenzo",
  "San Emilio",
  "Vecinos de las Praderas",
  "Los Dos Potreros",
  "El Ancón de Santa Anita",
  "Miramar",
  "Vivero del Estero",
  "Mi Ranchito",
  "Los Brellalitos",
  "El Cardoncito",
  "Cuesta de la Paloma",
  "El Agua Mala",
  "El Rosario",
  "Rancho Flores",
  "Los Dos Hermanos",
  "Rancho de Arámburo",
  "El Agua de la Yegua",
  "El Oasis",
  "La Ceiba",
  "Las Dos Marías",
  "El Taste de Santa Rosa",
  "Los Cardoncitos",
  "Los Cuates",
  "El Guayabito",
  "El Parral",
  "El Zalate",
  "Encinalito II",
  "La Herencia",
  "La Lomita",
  "San Gregorio",
  "Las Golondrinas",
  "Retiro la Hacienda",
  "Eco Adventure",
  "La Cuesta",
  "6 Hermanos",
  "El Laurel",
  "Migriño [Fraccionamiento]",
  "La Gorra",
  "La Cruz",
  "El Mautal",
  "Las Vistas",
  "Matancita",
  "El Rodeíto",
  "Cabo Blanco",
  "El Mezquitito",
  "Rancho los González",
  "La Bebelama",
  "El Potrero",
  "Los 3 Juanes",
  "El Bailarín",
  "El Ciruelito",
  "El Frijolito",
  "El Amigo",
  "La Tinaja",
  "Amanecer",
  "San Juanito",
  "El Malquerido",
  "Palo Hueco",
  "Buena Vista",
  "La Ilama",
  "La Biznaga",
  "Costa Palmas",
  "Arroyo Don Guillermo",
  "Los Tres Reparos",
  "Rancho Santos",
  "El Bitache",
  "Los Toritos",
  "Las Hortensias",
  "Tres Marías",
  "Hacienda Escondida",
  "Las Margaritas",
  "San Blas",
  "Materiales Hermanos Rubio",
  "San Francisco [Rancho]",
  "El Bateque",
  "La Mar",
  "Club Campestre el Madrigal",
  "Los Girasoles",
  "Santa Gregoria [Rancho]",
  "Los Cimbrones",
  "Prana del Mar",
  "Campamento Hermés",
  "María Amelia",
  "Vista Nueva",
  "Poza Blanca",
  "La Guadalupana",
  "El Reparo",
  "La Arbolada"
]