export const MulegeTownshipTowns = [
  "Santa Rosalía",
  "El Aguajito",
  "Año Nuevo",
  "Arroyo las Vacas",
  "Bahía Asunción",
  "Bahía Tortugas",
  "La Bocana",
  "Buenavista",
  "Las Calabazas",
  "La Candelaria",
  "El Caracol",
  "El Carricito",
  "El Coyote",
  "Las Cruces",
  "El Dátil",
  "La Esperanza",
  "Estero de la Bocana",
  "Cantil Colorado",
  "Guamúchil",
  "Guerrero Negro",
  "Gustavo Díaz Ordaz",
  "Isla Natividad",
  "Isla San Marcos",
  "Los Mártires",
  "El Mezquital",
  "Heroica Mulegé",
  "El Porvenir",
  "Punta Blanca",
  "Puerto Nuevo",
  "Punta Abreojos",
  "Punta Chivato",
  "Punta Eugenia",
  "Punta Prieta",
  "San Ángel",
  "San Bartolo",
  "San Bruno",
  "San Francisco de la Sierra",
  "San Ignacio",
  "La Enramada de San Javier",
  "San Joaquín",
  "San José de Castro",
  "San José de Gracia",
  "San José de Magdalena",
  "San Lino",
  "Ejido San Lucas",
  "San Pablo",
  "San Quintín",
  "San Roque",
  "San Sebastián",
  "Santa Águeda",
  "San Zacarías",
  "El Sauce",
  "El Sauzal",
  "El Sauzalito",
  "El Tablón",
  "Tata Viejo",
  "El Valle",
  "Los Gatos",
  "Las Tres Vírgenes",
  "Colonia Laguneros",
  "Emiliano Zapata",
  "Ejido Licenciado Alfredo Vladimir Bonfil",
  "San Hipólito",
  "San Miguel",
  "Crucero del Pacífico",
  "Guillermo Prieto",
  "Palo Verde",
  "Playa Buenaventura",
  "El Agua Verde",
  "San Nicolás",
  "El Potrero",
  "Rancho Nuevo",
  "San Juan",
  "San Gregorito",
  "El Chebo",
  "Punta Quebrada",
  "El Queen",
  "Malarrimo",
  "Campo René",
  "El Cuarenta",
  "San Francisquito",
  "San Esteban",
  "Santo Tomás",
  "El Perdido",
  "Las Cuevitas",
  "El Higuajín",
  "Jesús María",
  "Playa el Requesón",
  "Las Bebelamas",
  "El Consuelo",
  "Campo Delgadito",
  "Los Cerritos",
  "La Cueva",
  "Las Flores",
  "Las Huertas",
  "La Loma",
  "San Carlos Viejo",
  "San Hilario",
  "San Jacinto",
  "Santa Mónica",
  "El Silencio",
  "Villa Alberto Andrés Alvarado Arámburo",
  "El Palo Verde",
  "El Aguajito de Bermúdez",
  "El Aguajito de Santa Adelaida",
  "El Aguajito de las Mujeres",
  "El Álamo",
  "El Arrepentido",
  "La Ascensión",
  "El Azufre",
  "La Base",
  "El Batequi",
  "El Batequito",
  "Benito Juárez",
  "La Bombita",
  "Los Caballos",
  "Campo Pachico",
  "Canta Rana",
  "El Cantil Alto",
  "El Cardón",
  "Kuyimá",
  "Las Cañadas",
  "La Cerquita",
  "Cerro Gordo",
  "El Chamizal",
  "El Chirrión",
  "El Contadero",
  "La Cueva Colorada",
  "El Ranchito",
  "Francisco J. Mújica",
  "Gustavo Díaz Ordaz Segunda Etapa",
  "La Destiladera",
  "El Devisaderito",
  "San Julio",
  "El Dorado",
  "La Pitahaya",
  "El Edén",
  "Guadalupe",
  "La Fortuna",
  "La Freidera",
  "El Gachupín",
  "El Intermedio",
  "El Corral Grande",
  "Los González",
  "Guadalupe Segundo",
  "La Higuera",
  "Las Higueras",
  "La Higuerita",
  "Los Hornitos",
  "El Güeribito Uno",
  "Las Huertitas",
  "El Injerto",
  "La Joya",
  "Quichule [Restaurante]",
  "Las Lagunetas",
  "La Lagunita",
  "El Llano Redondo",
  "El Llano",
  "El Manglito",
  "Las Mariolas",
  "Las Matancitas",
  "El Mezcal",
  "Posada Concepción",
  "El Paraje",
  "Los Patos",
  "El Patrocinio",
  "Los Pilares",
  "Centro de Rehabilitación Caridad",
  "Playa Santispac",
  "La Presa",
  "Prosperidad",
  "Puerto Escondido",
  "Playa Punta Arena",
  "La Ramadita",
  "La Ranchería",
  "El Chávez",
  "La Reforma",
  "El Represito Dos",
  "El Represo",
  "El Rincón",
  "El Rodeo",
  "Las Margaritas",
  "El Salto",
  "San Alfonso",
  "El Corralón",
  "San Casimiro",
  "San Cristóbal",
  "San Dieguito",
  "San Estanislao",
  "San Francisco",
  "Los Batequis",
  "San Javier",
  "San Juan de la Pila",
  "San Luis",
  "San Marcos",
  "Santa María",
  "San Martín",
  "San Matías",
  "San Narciso",
  "San Patricio",
  "La Casa de Enmedio",
  "San Rafael",
  "San Regis",
  "San Simón",
  "San Tadeo",
  "San Valentín",
  "San Vicente",
  "Santa Ana",
  "Santa Brígida",
  "Santa Cruz",
  "Santa Isabel",
  "Santa Lucía",
  "Santa Martha",
  "Santa Rosa",
  "Santa Teresita",
  "Santo Domingo",
  "Los Sauces",
  "Las Sábilas",
  "La Palma",
  "La Soledad",
  "El Tajito",
  "El Tajo",
  "Las Tasajeras",
  "El Tecolote",
  "La Tinaja",
  "Las Tinajitas",
  "Las Palmas",
  "La Trinidad",
  "El Tule",
  "Las Tunas",
  "Uña de Gato",
  "Valladares",
  "La Ventana",
  "El Vergel",
  "La Vinorama",
  "Vivelejos",
  "La Vuelta",
  "El Zorrillo",
  "La Angostura",
  "Los Chepinos",
  "La Cañada",
  "Los Dolores",
  "Las Palmitas",
  "El Pozo",
  "Los Pronunciados",
  "El Chester",
  "La Rinconada",
  "El Rosarito",
  "San Alberto",
  "San Ramón",
  "Las Tinajas",
  "Los Girasoles",
  "La Lobera",
  "Los Santitos",
  "Estación las Ocho Bombas",
  "Los Crestones",
  "Guadalupe Tercero",
  "El Indio",
  "San Fernando",
  "El Mezquitalito",
  "Palo de Rayo",
  "San Lucas",
  "Ángel César Mendoza Arámburo",
  "Las Juntas",
  "El Estribo",
  "La Escalera",
  "San Roberto [Granja]",
  "Kilómetro 60-A",
  "Las Zayas",
  "El Nuevo Esfuerzo",
  "San Jerónimo",
  "El Pie de la Cuesta",
  "Los Llanitos",
  "El Barranco",
  "Los Higuajines",
  "Villas Mulegé",
  "El Triunfo",
  "San Antonio",
  "San Venancio",
  "El Motor",
  "San Andrés",
  "San Isidro",
  "Palapas el Burro",
  "Playa Escondida",
  "Centro de Readaptación Social",
  "San Luciano",
  "Agua Verde",
  "El Pavorreal 2",
  "San Benito",
  "La Mina Negra",
  "La Hacienda",
  "El Agua Escondida",
  "Boca de Chapala",
  "La Y",
  "El Cochi",
  "El Huérivo",
  "Punta el Nido",
  "San Juan del Pollo",
  "Unión y Progreso",
  "Punta Gorda",
  "El Atajo",
  "Kilómetro 60-B",
  "Boca de Magdalena",
  "Palo Verde [Acueducto]",
  "Los Tres Rafaeles",
  "Las Golondrinas",
  "Agua Amarga",
  "Rancho Guadalupe",
  "El Tovari",
  "San Gregorio",
  "Los Corrales",
  "El Aguaje de los Indios",
  "El Progreso",
  "El Trébol",
  "El Saladito",
  "El Madrazo",
  "Matarranchos",
  "La Cachora",
  "El Sayalito",
  "El Pato de la Angostura",
  "El Pato",
  "La Vela",
  "Los Americanos",
  "Los Flores Uno",
  "El Establo",
  "Los Naranjos",
  "El Mezquitón",
  "Los Compadres",
  "Playa los Naranjos",
  "La Huerta de la Cueva",
  "Playa los Cocos",
  "El Vizcaíno [Acueducto]",
  "Arroyo Verde",
  "La Bebelama",
  "El Carpintero",
  "El Carrizalito",
  "El Doroteo",
  "Ejido Luis Echeverría",
  "El Japón",
  "Los Muertitos",
  "El Norte",
  "Pancho Ramos",
  "Las Paredes",
  "Playa el Coyote",
  "Rancho Santiago",
  "Ninguno",
  "La Salina",
  "Los Salitrales",
  "El Represito",
  "El Chaparral",
  "La Ciénega",
  "La Esmeralda",
  "Estero el Coyote",
  "La Huerta",
  "La Huertita",
  "La Noria",
  "El Paso del Indio",
  "La Piedra Rajada",
  "La Presita",
  "Caopas [Compañía Minera]",
  "El Ayub",
  "La Berrenda",
  "El Sinaloa",
  "San Felipe",
  "El Palomar",
  "Ninguno [Bahía Tortugas]",
  "Kuyimita",
  "Nueva Prosperidad",
  "Punta Verde",
  "Colonia Nueva Esperanza",
  "El Corralito",
  "Don Juanito",
  "El Agua Caliente",
  "El Agüita",
  "Campamento Cimarrón",
  "Casa Hogar [Centro de Rehabilitación]",
  "El Cerival",
  "La Cueva de Gel",
  "Oasis el Edén",
  "El Escritorio",
  "El Güeribito Dos",
  "El Fuste",
  "El Lomboyal",
  "Las Matitas",
  "El Mezquitito",
  "Campamento del Borrego Cimarrón",
  "El Palmarito",
  "La Puerta",
  "Tres Hermanos",
  "Tres Milagros",
  "El Represito Uno",
  "El Sacrificio",
  "Los Tepetates",
  "Las Tierras",
  "Unidad Pecuaria ZA-5",
  "La Baliza",
  "Belisario Domínguez",
  "Los Bules",
  "Los Garbancillos",
  "La India",
  "La Isla",
  "El Llanito",
  "Matancitas",
  "El Médano Amarillo",
  "Nueva Santa Elena",
  "El Paraíso",
  "Piedras Negras",
  "Rancho Viejo",
  "El Saltito",
  "Santa Martha de la Costa",
  "Los Juncos",
  "Rancho Zazueta",
  "El Condorito",
  "El Planecito",
  "Loma Linda",
  "La Tobillera",
  "El Raizudo",
  "Llanito de los Burros",
  "Los Romeros",
  "El Tangaliote",
  "Campamento de la Ballena Gris",
  "La Estación",
  "El Necio",
  "Doctor Belisario Domínguez",
  "Los Flores Dos",
  "El Pozo 15",
  "Los Huizar",
  "Las Trancas",
  "El Cóndor",
  "Los Torotes",
  "La Víbora",
  "El Borjas",
  "Santa Cleotilde",
  "La Herradura",
  "La Morenita",
  "El Sufrimiento",
  "La Minita",
  "Dos Amigos [Trailer Park]",
  "Balandra [Restaurante]",
  "RVP Ejido San Lucas",
  "Los Olivares",
  "Pescadores del Mar de Cortés [SCPP]",
  "El Brumar",
  "Campo Cortés",
  "El Chilenito",
  "El Llano Dos",
  "El Llano Tres",
  "El Regalo",
  "La Bahía",
  "La Bandera",
  "La Cañadita",
  "Zavalas",
  "La Palma Dos",
  "La Roca [La Granja]",
  "Los Potrillos",
  "Playa Santa Inés",
  "Carmelita [Restaurante]",
  "San Isidro Uno",
  "Santa Inés",
  "El Socorro",
  "El Mezquite",
  "El Tastesito",
  "Los Pinos",
  "San Sebastián Dos",
  "Dulce Baja",
  "Conjunto Habitacional Santa Águeda",
  "Loma Dorada",
  "El Aferrado",
  "Los Montaños",
  "Los Angeles",
  "Aullido del Lobo",
  "Go Anda",
  "Corralejos",
  "Ermita",
  "Las Granjitas",
  "Quinta Gloria",
  "Santa Brigida",
  "El Zafiro",
  "El Mezquital Dos",
  "Los Huizapoles",
  "Casas Viejas",
  "PAW [Clínica Veterinaria]",
  "El Tanque de Sotelo",
  "Guizaga [Orgánicos]"
]